name: inventory
env:
  CI: false
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: CI=false npm run build
      - run: npm test
     
